"""
pdf_generator.py
"""

import re
from fpdf import FPDF


def sanitize(text: str) -> str:
    replacements = {
        "\u2192": "->", "\u2190": "<-", "\u2194": "<->",
        "\u2013": "-", "\u2014": "--",
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2026": "...", "\u00a0": " ",
        "\u2022": "-", "\u2605": "*", "\u2606": "*",
        "\u2714": "(yes)", "\u2717": "(no)", "\u00b7": "-",
        "\u00e9": "e", "\u00e8": "e", "\u00ea": "e",
        "\u00e0": "a", "\u00e2": "a",
        "\u00f9": "u", "\u00fb": "u",
        "\u00ee": "i", "\u00ef": "i",
        "\u00f4": "o", "\u00e7": "c",
        "\u00fc": "u", "\u00f6": "o", "\u00e4": "a",
        "\u00df": "ss", "\u00b0": " degrees",
        "\u00d7": "x", "\u00f7": "/", "\u2212": "-",
        "\u00ae": "(R)", "\u00a9": "(C)", "\u2122": "(TM)",
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    text = text.encode("latin-1", errors="ignore").decode("latin-1")
    return text


class ArticlePDF(FPDF):
    def __init__(self, video_title: str):
        super().__init__()
        self.video_title = sanitize(video_title)
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(left=20, top=20, right=20)

    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, "YouTube -> Insightful Article", align="L")
        self.ln(6)
        self.set_draw_color(220, 220, 220)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by YT Article Generator", align="C")


def clean_markdown(text: str) -> list[tuple[str, str]]:
    segments = []
    for line in text.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue
        stripped = sanitize(stripped)
        if stripped.startswith("### "):
            segments.append(("h3", stripped[4:]))
        elif stripped.startswith("## "):
            segments.append(("h2", stripped[3:]))
        elif stripped.startswith("# "):
            segments.append(("h1", stripped[2:]))
        else:
            cleaned = re.sub(r"\*\*(.+?)\*\*", r"\1", stripped)
            cleaned = re.sub(r"\*(.+?)\*", r"\1", cleaned)
            segments.append(("body", cleaned))
    return segments


def generate_pdf(article: str, video_title: str) -> tuple[bytes, str | None]:
    try:
        pdf = ArticlePDF(video_title)
        pdf.add_page()
        segments = clean_markdown(article)

        for seg_type, content in segments:
            if seg_type == "h1":
                pdf.set_font("Helvetica", "B", 20)
                pdf.set_text_color(20, 20, 20)
                pdf.multi_cell(0, 10, content)
                pdf.ln(3)
            elif seg_type == "h2":
                pdf.ln(4)
                pdf.set_font("Helvetica", "B", 14)
                pdf.set_text_color(40, 40, 40)
                pdf.multi_cell(0, 8, content)
                pdf.set_draw_color(255, 107, 53)
                pdf.set_line_width(0.5)
                pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + 40, pdf.get_y())
                pdf.ln(4)
            elif seg_type == "h3":
                pdf.ln(3)
                pdf.set_font("Helvetica", "B", 12)
                pdf.set_text_color(60, 60, 60)
                pdf.multi_cell(0, 7, content)
                pdf.ln(2)
            else:
                pdf.set_font("Helvetica", "", 11)
                pdf.set_text_color(50, 50, 50)
                pdf.multi_cell(0, 6.5, content)
                pdf.ln(2)

        pdf_bytes = bytes(pdf.output())
        return pdf_bytes, None

    except Exception as e:
        return b"", f"PDF generation error: {e}"